name: Deploy Web App su GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'
      - 'css/**'
      - 'js/**'
      - 'data/**'
      - 'manifest.json'
      - 'sw.js'
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configurazione GitHub Pages
        uses: actions/configure-pages@v5

      - name: Caricamento Artifacts Web App
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Pubblicazione su GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
